### ISSUE TITLE
AwsAurora DDL generation should escape table and column names.

### ISSUE THREAD

**Issue by zednis** [konigio/konig#1091]
The aws plugin which generates DDL for aurora does not escape table or column names.  This leads to problems in cases where the intended column name is a reserved keyword in SQL.  Our current naming conventions for datamart dimension tables will hit this issue with the KEY column.

currently generated SQL:
```sql
KEY INT NOT NULL,
...
PRIMARY KEY (KEY)
```

escaped SQL:
```sql
`KEY` INT NOT NULL,
...
PRIMARY KEY (`KEY`)
```

For simplicity, I suggest the DDL generation escape all table and column names.

**Comment by gmcfall** [comment]
The implementation quotes table and column names that match a MySQL reserved word.
