### ISSUE TITLE
Identifier for individuals getting generated as NULL

### ISSUE THREAD

**Issue by nbalakri** [konigio/konig#123]
1) Even though "Code Value" are defined in the  "Individuals" Tab, output files in Data Folder are getting generated with Identifier defaulted as NULL.

2) DealProductScopeType - Data file has no values. Looks like none of the defined controlled vocabulary  has code values defined.

**Comment by konigio** [comment]
The root cause of the null "indentifier" field was an inconsistent use of Dublin Core namespaces.  In some places we were using Dublic Core Elements (http://purl.org/dc/elements/1.1/) and in other places we were using Dublin Core Terms (http://purl.org/dc/terms/)

**Comment by konigio** [comment]
With this fix, we are now using Dublin Core consistently.  We always use the Dublin Core Terms namespace.
