### ISSUE TITLE
Full Deployment

### ISSUE THREAD

**Issue by gmcfall** [konigio/konig#1361]
I want a Maven profile that will perform a full deployment to a given environment (dev, test, staging, prod).

### Acceptance Criteria

- There shall be a generated maven pom.xml file which manages the deployment process for an entire project.
- This pom.xml file shall be located at `target/deploy/pom.xml`.
- It must be possible to perform a full deployment to a given environment via the following commands:
```
   cd target/deploy
   mvn install -Denvironment={environmentName} -P deploy-all 
```
- The `deploy-all` profile shall perform the following actions:
   - Run the Google Deployment Manager to deploy all resources to the Google Cloud.
   - Create all Dataflow pipeline templates

### Notes:
We already have a POM file at `target/deploy/pom.xml`.  Currently, this POM only supports the packaging of the build artifacts into a collection of zip files.  We need to enhance this generated POM so that it includes the `deploy-all` profile that will perform the deployment actions.  The class that generates the POM is `io.konig.schemagen.packaging.MavenPackagingProjectGenerator`.

**Comment by Uvashriamm** [comment]
To perform the full deployment 

```
cd target/deploy

mvn install exec:exec -Pdeploy-all -DenvironmentName=${environmentName}

```
