### ISSUE TITLE
Bug in Beam Transform for enum

### ISSUE THREAD

**Issue by gmcfall** [konigio/konig#1406]
The `BeamTransformGeneratorTest.testEnumMapping()` method generates class `com.example.beam.etl.shape.ToPersonTargetShapeFn` which contains the following method...

````
private void transformGender(TableRow inputRow, TableRow outputRow) {
        Object gender_code = inputRow.get("gender_code").toString();
        if (gender_code!= null) {
            GenderType gender = GenderType.findByGenderCode(gender_code);
            TableRow genderRow = new TableRow();
            Object id = gender.getId();
            if (id!= null) {
                genderRow.set("id", id.toString());
            }
            Object name = gender.getName();
            if (name!= null) {
                genderRow.set("name", name);
            }
            genderRow.set("genderCode", gender_code);
            outputRow.set("gender", genderRow);
        }
    }
````

The following line is problematic:
```
        Object gender_code = inputRow.get("gender_code").toString();
```

If `inputRow.get("gender_code")` returns a null value, then we get a null-pointer exception.

To fix it, the generator should produce the following code instead...
```

private void transformGender(TableRow inputRow, TableRow outputRow) {
        Object gender_code = inputRow.get("gender_code");
        if (gender_code!= null) {
            gender_code = gender_code.toString();
            GenderType gender = GenderType.findByGenderCode(gender_code);
            ...
```

**Comment by Uvashriamm** [comment]
The above issue got fixed in #1397 

The other issue is 

``
private boolean gender(TableRow outputRow, ErrorBuilder errorBuilder) {
        Object personSourceRow_gender_code = personSourceRow.get("personSourceRow_gender_code");
        if (personSourceRow_gender_code!= null) {
            TableRow genderRow = new TableRow();
            GenderType gender = GenderType.findByGenderCode(personSourceRow_gender_code.toString());
            gender_id(gender, genderRow, errorBuilder);
            gender_name(gender, genderRow, errorBuilder);
            genderRow.set("genderCode", personSourceRow_gender_code);
            outputRow.set("gender", genderRow);
        }
    }
``
The code has compilation error and personSourceRow parameter was missed.

And also it should be corrected while invoking the method from processElement

``
gender(outputRow, errorBuilder);
``
