### ISSUE TITLE
Enum Reference Data for metis-gbi-uk customer model

### ISSUE THREAD

**Issue by gmcfall** [konigio/konig#1537]
The konig build tool is supposed to generate BigQuery tables for each enumeration class declared in the semantic workbook, and it is supposed to generate scripts to load those tables with data.  This feature does not appear to be working for the metis-gbi-uk.  

Either the pom.xml file for the project needs to be updated, or there is a bug that needs to be fixed.

**Comment by Uvashriamm** [comment]
We have add the below configuration in pom.xml

```
<googleCloudPlatform>
	<enableBigQueryTransform>true</enableBigQueryTransform>		<bigqueryEnumShapeIriTemplate>https://schema.pearson.com/shapes/{targetClass.localName}Shape</bigqueryEnumShapeIriTemplate>
	<omitTypeFromEnumTables>true</omitTypeFromEnumTables>
</googleCloudPlatform>

```
