### ISSUE TITLE
Sum of count across the dimension

### ISSUE THREAD

**Issue by Uvashriamm** [konigio/konig#557]
I have a metric to compute the measure for the dimensions, But also I want to compute the measure for all the values of the dimension

For eg. I want to get the unique count students of the grades across the all the schools

**Comment by gmcfall** [comment]
Can you clarify the example.  I think you mean the following:

> I want to get the number of students at a given grade level across all schools in some geographical region (city, state, country, etc.)

Is this correct?

**Comment by gmcfall** [comment]
This is a duplicate of #556
