### ISSUE TITLE
Authenticating API Request

### ISSUE THREAD

**Issue by Uvashriamm** [konigio/konig#592]
To authenticate the API Request, I want to validate the ClientID and ClientSecret from the HttpRequest Header.

**Comment by gmcfall** [comment]
This should be implemented using the [Basic Access protocol](https://en.wikipedia.org/wiki/Basic_access_authentication)

Username/password pairs should be stored in Google Datastore.

The database should store the SHA1 hash of the password (not the raw password).
The application should cache the SHA1 hash of the password  using memcache for performance.  The username should be used as the key to lookup the SHA1 hash of the password from the cache.

To get started, we can use the Datastore Console to manually enter valid username/sha1(password) pairs into Datastore.  Later, we can add an administrative UI to manage the password.

**Comment by gmcfall** [comment]
Did not mean to close the issue
