### ISSUE TITLE
Generate and build multi-project with single command

### ISSUE THREAD

**Issue by gmcfall** [konigio/konig#599]
We have the ability to generate a "multi-project" that consists of a parent project plus a collection of child projects.

Once the suite of maven projects is generated, you have to run a separate command to build them.

There should be a configuration parameter to automatically build the maven projects once they are generated.

### Acceptance Criteria
* Add a configuration parameter named `autoBuild` that takes a boolean value.  
* If `autoBuild=true` then once the multi-project is generated, the Konig generator plugin should automatically run the build script on the generated parent project.  The goals for the current maven build should be passed to the generated parent project.
* The `autoBuild` parameter should be true by default.
* It must be possible to specify the `autoBuild` parameter from the command line (not only in the pom.xml file).

**Comment by zednis** [comment]
I have been manually configuring on a multi-module model project for the OneCRM model in the Pearson bitbucket.

https://bitbucket.pearson.com/projects/METIS/repos/metis-onecrm/browse

Regarding the acceptance criteria, what if the multi-module project was built from a maven archetype?  An ``autoBuild`` parameter would not be necessary and we could use the standard mvn options for specifying builds of only specific modules of the project.

Note, my understanding was that this effort was in the context of a model project such as mypedia or mdm, the repos that we normally store in The METIS Pearson BitBucket project.

cc: @gmcfall
