### ISSUE TITLE
Publish Data Catalog for Rights&Permissions project

### ISSUE THREAD

**Issue by gmcfall** [konigio/konig#637]
The semantic model for the Rights&Permissions project needs to be updated to reflect current best practices and the data catalog for this project must be published.

### Acceptance Criteria
* There must exisit a Bitbucket project named `metis-rights` in https://bitbucket.pearson.com/projects/METIS
* The `metis-rights` Bitbucket project must contain a Maven "multi-project" named `metis-rights-generator` (similar to `metis-mypedia-generator`
   * The `metis-rights-generator` project must produce an RDF/SHACL model based on the [rights-and-royalties](https://docs.google.com/spreadsheets/d/1bYZFFoE0l6iftPglFVf_bE9zQfyr0KU1NQYAWMVVn2g/edit#gid=909425301) spreadsheet.
   * The `metis-rights-generator` project must create a data-catalog child project.
* The Rights&Permissions data-catalog must be published to `pearson-docs`.

### Notes
The `rights-and-royalties` spreadsheet is based on an earlier version of the Konig toolkit.  You may need to make some changes to the column names to get a successful build.

**Comment by Uvashriamm** [comment]
Published to [metis-rights-data-catalog](https://content-dot-pearson-docs.appspot.com/content/rights-and-royalties/1.0.0/)
