### ISSUE TITLE
Publish Data Catalog for Delivery Excellence project

### ISSUE THREAD

**Issue by gmcfall** [konigio/konig#638]
The semantic model for the Delivery Excellence project needs to be updated to reflect current best practices and the data catalog for this project must be published.

### Acceptance Criteria
* The [metis-delivery-excellence](https://bitbucket.pearson.com/projects/METIS/repos/metis-delivery-excellence/browse) Bitbucket project must contain a Maven "multi-project" named `metis-delivery-excellence-generator` (similar to `metis-mypedia-generator`)
   * The `metis-delivery-excellence-generator` project must produce an RDF/SHACL model based on the [rdelivery-excellence-model](https://docs.google.com/spreadsheets/d/1ba2_4tubQaGsN8_kJw3Gab8sL07g4BZgFUtNSkTuAPY/edit#gid=1419373143) spreadsheet.
   * The `metis-delivery-excellence-generator` project must create a data-catalog child project.
* The Delivery Excellence data-catalog must be published to `pearson-docs`.

### Notes
The `delivery-excellence-model` spreadsheet is based on an earlier version of the Konig toolkit.  You may need to make some changes to the column names to get a successful build.

**Comment by Uvashriamm** [comment]
Published to [metis-delivery-excellence-data-catalog](https://content-dot-pearson-docs.appspot.com/content/metis-delivery-excellence/1.0.0/index.html)
