### ISSUE TITLE
Publish consolidated data model

### ISSUE THREAD

**Issue by gmcfall** [konigio/konig#641]
We need to develop a maven project that merges the data models from individual projects (Rights&Permissions, Delivery Excellence, MyPedia) into a single, consolidated semantic model.  We need to publish the data catalog for the consolidated model.

### Acceptance Criteria
* The [metis-global](https://bitbucket.pearson.com/projects/METIS/repos/metis-global/browse) repository must contain a new maven project named `metis-global-merge`.
* The `metis-global-merge` project must include the *Konig Model Merge* plugin.  
   * This plugin must be configured to consolidate the semantic models from Rights&Permissions, Delivery Excellence, and MyPedia using the existing artifacts from these contributing projects.
   * The `metis-global` repository MUST NOT contain its own private copies of the contributing projects.
* The `metis-global-merge` project must include the *Konig Data Catalog* plugin.
* The `metis-global-merge` project must include the *Konig Content System* plugin configured to publish to `pearson-docs`.
* One must build the the `maven-global-merge` project so that its data catalog is, in fact, published to `pearson-docs`.

### Implementation notes
This issue should rely on [konig-model-merge-maven-plugin](https://github.com/konigio/konig/tree/master/konig-model-merge-maven-plugin)

For an example that shows how to use this plugin, take a look at [model-merge-root](https://github.com/konigio/konig-examples/tree/master/merge-model-root).

**Comment by Uvashriamm** [comment]
Published to [metis-global-model](https://content-dot-pearson-docs.appspot.com/content/metis-global-model/1.0.0/index.html)
