### ISSUE TITLE
Write CADLParser

### ISSUE THREAD

**Issue by zednis** [konigio/konig#663]
Develop a Cube Algebra Definition Language (CADL) Parser to facilitate processing of data cubes defined using CADL.

base CADL example:
```
CUBE OppportunityExpectedRevenue {

	DIMENSION Date
	  LEVEL Day {date (date) UNIQUE}
	  LEVEL WeekOfYear {weekOfYear (integer), year (integer)}
	  LEVEL Month {month (integer), year (integer)}
	  LEVEL Quarter {quarter (integer), year (integer)}
	  LEVEL Year {year (integer) UNIQUE}
	  Day ROLL-UP to WeekOfYear
	  Day ROLL-UP to Month
	  WeekOfYear ROLL-UP to Year
	  Month ROLL-UP to Quarter
	  Quarter ROLL-UP to Year

	DIMENSION SalesTarget
	  LEVEL RevenueTarget ATTRIBUTES {name (string), startDate (date), endDate (date), targetRevenue (decimal), assignee (string)}

	DIMENSION Status
	  LEVEL Status ATTRIBUTES {name (string) UNIQUE}

	DIMENSION OpportunityType
	  LEVEL OpportunityType ATTRIBUTES {name (string)}

	DIMENSION Account
	  LEVEL Industry ATTRIBUTES {name (string)}
	  LEVEL AccountType ATTRIBUTES {name (string)}
	  LEVEL Account ATTRIBUTES {name (string), accountType (string), industry (string)}
	  Account ROLL-UP to AccountType
	  Account ROLL-UP to Industry

	DIMENSION Product
	  LEVEL Product ATTRIBUTES {name (string), isbn13 (string) UNIQUE}

	DIMENSION Sales
	  LEVEL Country {name(string)}
	  LEVEL SalesTerritory {name (string)}
	  LEVEL SalesPerson {id (string) UNIQUE, name (string), country (string)}
	  SalesPerson ROLL-UP to SalesTerritory
	  SalesPerson ROLL-UP to Country

	DIMENSION Currency REQUIRED
	  LEVEL Currency ATTRIBUTES {name (string) UNIQUE}

	MEASURE expectedRevenue (decimal)
	MEASURE opportunityCount (integer)
}
```
extensions to CADL will likely have to be defined to allow for a formal mapping of dimension, levels, attributes, and measures into semantic models.

related to #664

[CADL paper link](https://www.cise.ufl.edu/~mschneid/Research/papers/CCGSVZ13IJDWM.pdf)

**Comment by zednis** [comment]
@gmcfall for the CADLParser, where should I put the parser class?  io.konig.core.cadl in konig-core or as part of a konig-datacube module that would logically be created as part of #664?

**Comment by gmcfall** [comment]
Let's add a konig-datacube module

**Comment by zednis** [comment]
I implemented a parser using antlr4.

The grammar to CADL cube documents is defined as the following and the antlr runtime is used to generate source java files which can tokenize and parse this grammar.

CADL grammar:
```g4
grammar CADL ;

cube	: 'CUBE' NAME '{' (dimension)* (measure)* '}' ;

dimension	: 'DIMENSION' NAME (level)* (rollup)* ;

level	: 'LEVEL' NAME 'ATTRIBUTES' '{' (attribute)* '}';

measure	: 'MEASURE' NAME '(' datatype ')';

attribute : NAME '(' datatype ')' (UNIQUE)? (',')?;

UNIQUE : 'UNIQUE' ;

rollup :  NAME 'ROLL-UP to' NAME ;

datatype : 'real'|'string'|'date'|'integer' ;

NAME	: [a-zA-Z][a-zA-Z0-9]* ;

COMMENT : '#' ~([\r\n])* -> skip ;

WS : [ \t\r\n]+ -> skip ;
```

This grammar is used to generate a parse tree that looks like this
- ![cube2_parse_tree](https://user-images.githubusercontent.com/1057295/34883332-934e51d4-f776-11e7-9eee-f9392fbec74c.png)

The DataCubeListener was added to implement a SAX-like event-based listener which builds a DataCube POJO from values extracted from the ANTR parse tree.

The DataCubeParser class extends io.konig.parser.BaseParser and in its parse method it constructs the ANTLR parse tree and uses the DataCubeListener to build and return a DataCube POJO.

DataCubeParser:parse()
```
    public DataCube parse(Reader reader) throws IOException {

        CharStream input = CharStreams.fromReader(reader);
        CADLLexer lexer = new CADLLexer(input);
        CommonTokenStream tokens = new CommonTokenStream(lexer);
        CADLParser parser = new CADLParser(tokens);

        ParseTree tree = parser.cube();
        ParseTreeWalker walker = new ParseTreeWalker();
        DataCubeListener listener = new DataCubeListener();
        walker.walk(listener, tree);

        return listener.getDataCube();
    }
```
classes:
- [DataCubeParser](https://github.com/konigio/konig/blob/zednis/%23664/konig-datacube/src/main/java/io/konig/cadl/parser/DataCubeParser.java)
- [DataCubeListener](https://github.com/konigio/konig/blob/zednis/%23664/konig-datacube/src/main/java/io/konig/cadl/parser/DataCubeListener.java)

**Comment by zednis** [comment]
note - I committed this CADL parser to konig-datacube in the zednis/#664 branch as the parser is a part of the overall konig-datacube module which will provide data shape generation capabilities covered by #664

**Comment by zednis** [comment]
I am going to close out this ticket as the base CADL parser described by this ticket is working in unit tests. 

The parser will be updated to support as-of-yet undefined extensions introduced by #664 and will be part of the pull request for #664.
