### ISSUE TITLE
Support Pagination for Raw Json response

### ISSUE THREAD

**Issue by svenk9575** [konigio/konig#670]
Pagination
Specify the queryString parameter as .cursor=Zm9vPTIwMTctMTItMDU
Use "cursor-based pagination"

**Comment by zednis** [comment]
@svenk9575 Are we updating a konig class that is a client that supports the pagination feature of a called service, or implementing pagination on a konig API?

To put it another way, are we a consumer, a producer, or a pass-through for the paginated results?

**Comment by zednis** [comment]
Is there an example of what the Raw JSON output looks like?

**Comment by zednis** [comment]
Looking at the code for BigQueryShapeReadService.java, it looks like the current raw JSON response is a top-level array.  To support a nextPageToken field added to the JSON output we will need to change the JSON response to be an object (there is also a TODO comment in the code about changing the response to be an object that corresponds with LDP conventions).

If that is the case, we will need to update a response that looks like
```json
[
  {
    "givenName": "Alice"
  }
]
```

to a response that looks like:
```json
{
	"id": "...",
	"type": "BasicContainer",
	"pageToken": "...",
	"nextPageToken": "Zm9vPTIwMTctMTItMDU",
	"contains": [
		{
			"givenName": "Alice"
		}
	]
}
```

@gmcfall Do I understand the general requirements correctly?

**Comment by zednis** [comment]
Should the current page token (if pagination is set) be part of the response JSON, either has part of an id field (which would contain the URL of the request) or as the value of its own "pageToken" field?
