### ISSUE TITLE
Spike on Linked Data Platform Paging

### ISSUE THREAD

**Issue by svenk9575** [konigio/konig#710]
There is a proposal in the following link:
https://www.w3.org/2012/ldp/hg/ldp-paging.html

**Comment by gmcfall** [comment]
@svenk9575 would you please add acceptance criteria to this issue?  If this is a research spike what is the expected outcome of the spike?

**Comment by svenk9575** [comment]
The following document details out the design aspects
https://docs.google.com/document/d/1klm8NyP_R9lQ_PBSXv15R1eGj5h2PG4SaA-GBMVq-X4/edit?usp=sharing
