### ISSUE TITLE
Move Dockerfile produced by test case

### ISSUE THREAD

**Issue by gmcfall** [konigio/konig#843]
There seems to be a test case that generates the following file within the Konig source tree...

* `etl-localName/Docker/Dockerfile`

All files generated by test cases should go under the `target` directory of the relevant Maven project.
We need someone to track down the offending test case and fix it so that the output goes into the `target` directory -- not the Konig source tree.

**Comment by RanjaniGuru** [comment]
No longer an issue. Hence closing this.
