### ISSUE TITLE
Indicate primary keys on staging table data

### ISSUE THREAD

**Issue by zednis** [konigio/konig#854]
When defining source shapes for representing staging tables, we should be able to indicate primary keys on source data to inform generated UPSERT queries for loading staging tables.

### Acceptance Criteria
* ~Any sheet that defines property constraints must support columns named ``Primary Key``~
* ~For any property constraint that is primary key, or a component of a composite primary key, for a source/origin data shape, the ``Primary Key`` column should contain the value ``Y``, otherwise it should be left blank.~
* Introduce ``konig:primaryKey`` as an allowed value in the ``stereotype`` column of the property constraints tab to indicate that a property should be considered a primary key for the relevant data shape.
* ~The ``Primary Key`` column should not be used for non-source/origin data.~
* UPSERT queries generated for loading the staging tables should make use of these primary keys to determine if an existing records should be updated.

**Comment by zednis** [comment]
I am fine with introducing konig:primaryKey as an allowed value in the ``stereotype`` column.

**Comment by zednis** [comment]
@muralim01

**Comment by ElakiyaUdhayanan** [comment]
This issue was taken care as a part of issue number 786 (MySQL Upsert). Hence closing the issue.
