### ISSUE TITLE
Guidelines for designing data mart views

### ISSUE THREAD

**Issue by gmcfall** [konigio/konig#864]
As a business analyst, I want guidelines to help me design data mart views so that I can increase the chances of getting my views approved by the Governance board.

### Acceptance Criteria
* There must be *Data Mart View Design Guidelines* document in Google Drive.
* The guidelines must include naming conventions for properties exposed by the view. 
* The naming conventions must include rules for flattening a data model in the view.
* The guidelines must include a specification for the artifacts that will be submitted to the Governance Board for review.
* The artifacts must include the SQL DDL (*CREATE VIEW* statement) that is being proposed.
* The artifacts must include a definition of the properties exposed by the view.  (You'll need to specify the exact mechanism for defining the properties.  Possibilities include comments in the SQL DDL or a separate spreadsheet.)
* There must be a way to generate a SHACL Shape for the proposed view so that it can be published to the Data Catalog.  Consequently, there will need to be some way to connect the property definitions to the values in the view, and there must be some way to identify the data type for each value -- either through analysis of the source tables or included in property definitions.

**Comment by zednis** [comment]
I have created a [Data Mart / ODS Design Guidelines doc](https://docs.google.com/document/d/1piQPHjXTcnqAC3gRbQZ4CuwDqpneekDO7whWZ5AnMIw/edit#) and added it to the EDW shared Google Drive.
