### ISSUE TITLE
Generate relational model using SNAKE_CASE

### ISSUE THREAD

**Issue by gmcfall** [konigio/konig#891]
Given a *logical* Shape as input, I want the Konig toolkit to generate a *physical* model using SNAKE_CASE for the property names so that the physical model follows best-practice naming conventions for relational databases.

### Acceptance Criteria

* There must be a utility named `RdbmsShapeGenerator` that takes as input one Shape and produces as output a new Shape where the properties have been modified as follows:
   * Local names in *camelCase* or *PascalCase* must be replaced by local names in *SNAKE_CASE*.  For example, the name `salesAgentEmail` would be replaced by `SALES_AGENT_EMAIL`. 
   * Local names that use lowercase *snake_case* must be replaced by uppercase *SNAKE_CASE*.  For example, the name `sales_agent_email` would be replaced by `SALES_AGENT_EMAIL`.
   * The namespace URI for modified property names must be configurable.  
   * Local names that already use uppercase *SNAKE_CASE* must NOT be modified.
* If there are no changes to any of the property names, the utility shall not generate a new shape and shall  return `null`.
* The IRI for the generated Shape shall be defined by a regular expression pattern and a replacement pattern supplied by the user.  Suppose, for example, that the user supplies the regular expression `(.*)Shape$` and the replacement pattern `$1RdbmsShape`.  In this case, if the IRI for the original shape is `SalesTransactionShape`, then the IRI for the generated shape would be `SalesTransactionRdbmsShape`.
* If the IRI for the original shape does not match the regular expression and there are properties that would otherwise be renamed,  the `RdbmsShapeGenerator` shall log a warning, and return `null`.   It must NOT throw an exception in this case.
* The class `io.konig.maven.AmazonWebServicesConfig` must have a new field named `aurora` of type `io.konig.maven.AuroraInfo`.
* Each of the classes `io.konig.maven.BigQueryInfo`, `io.konig.maven.CloudSqlInfo`, `io.konig.maven.AuroraInfo` must accept a new child element of the form:

```
   <rdbmsShapeGenerator>
      <shapeIriPattern>some-regex-pattern</shapeIriPattern>
      <shapeIriReplacement>the-replacement-pattern</shapeIriReplacement>
   </rdbmsShapeGenerator>
```

* If the `rdbmsShapeGenerator` element is present, then
   * The Konig toolkit shall invoke the `RdbmsShapeGenerator` for Shapes that have a `DataSource` of the associated type (`GoogleBigQueryTable`, `GoogleCloudSqlTable`, or `AwsAurora`). 
   * If the `RdbmsShapeGenerator` returns a non-null Shape as output, then the Konig toolkit shall:
      * Modify the original Shape by moving the DataSource to the generated Shape.
      * Save the original Shape (without the associated DataSource) in its original Turtle file.
      * Save a new Turtle file containing the Shape produced by the `RdbmsShapeGenerator` with the DataSource from the original Shape.

* There must be a unit test for the `RdbmsShapeGenerator`.
* There must be an example in the `konig-examples` repository that illustrates the use of the `RdbmsShapeGenerator`.

### Implementation Notes

* The `RdbmsShapeGenerator` should be invoked by `KonigSchemagenMojo` immediately after loading resources and before any other processing.  We should add a method named `preprocessResources()` as shown by the comment in the snippet below.  We should invoke the `RdbmsShapeGenerator` inside the `preprocessResources()` method.

```
public void execute() throws MojoExecutionException   {
    	
  try {
    init();
    shapeManager = new MemoryShapeManager();
    nsManager = new MemoryNamespaceManager();
    mediaTypeNamer = new SimpleShapeMediaTypeNamer();
    owlGraph = new MemoryGraph();
    contextManager = new MemoryContextManager();
    owlReasoner = new OwlReasoner(owlGraph);
    owlGraph.setNamespaceManager(nsManager);

    loadResources();
//  preprocessResources();
  
    generateGoogleCloudPlatform();
    generateOracleManagedCloudServices();
    generateAmazonWebServices();
   ...

```

**Comment by gmcfall** [comment]
@zednis Let us know if you recommend any changes to the description of this issue.  We will be adding other features to `RdbmsShapeGenerator`, but let's start with the ability to generate SNAKE_CASE.

**Comment by zednis** [comment]
I think there are a few additional logical -> (relational) physical shape mapping issues that we should address, either in this ticket or in related tickets.

1) handling one-to-one entity relationships
2) handling one-to-many relationships
2b) handling ordering of items from one-to-many relationships

## 1. handling one-to-one entity relationships

In cases where there is a one-to-one entity relationship in the logical model, it should be possible to generate the physical model with the dependent entity flattened into it its parent entity.  When flattening a dependent entity into its parent the computed physical shape property should be based on the property path from the parent object to the dependent entity's property with a double underscore used as the property delimiter.

For example, path ``.address.streetAddress`` would be mapped to ``alias:ADDRESS__STREET_ADDRESS`` in the physical shape.

example JSON
```json
{
  "givenName": "John",
  "familyName": "Doe",
  "address": {
    "streetAddress": "359 Hidden Pond Road",
    "addressLocality": "Franklin",
    "addressRegion": "TN",
    "addressCountry": "US",
    "postalCode": "37067"
  }
}
```
 Logical Shape

 | Shape Id  | Property Id | Formula | Value Type | Value Class | Min Count | Max Count | Stereotype | Max Length |
| ------------- | ------------- | ------------- | ------------- |  ------------- |------------- | ------------- | ------------- | ------------- |
| shape:PersonShape | schema:givenName | | xsd:string | | 0 | 1 |  | 55 |
| shape:PersonShape | schema:familyName  | | xsd:string | | 0 | 1 |  | 55 |
| shape:PersonShape | schema:address | | shape:PersonAddressShape | schema:PostalAddress | 0 | 1 |  | |
| shape:PersonAddressShape | schema:streetAddress | | xsd:string | | 0 | 1 |  | 55  |
| shape:PersonAddressShape | schema:addressLocality | | xsd:string | | 0 | 1 |  | 55 |
| shape:PersonAddressShape | schema:addressRegion | | xsd:string | | 0 | 1 |  | 55 |
| shape:PersonAddressShape | schema:addressCountry | | xsd:string | | 0 | 1 |  | 55 |
| shape:PersonAddressShape | schema:postalCode | | xsd:string | | 0 | 1 |  | 55 |

Resulting physical shape

| Shape Id  | Property Id | Formula | Value Type | Min Count | Max Count | Stereotype | Max Length |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| shape:PersonRDBMSShape | alias:GIVEN_NAME | .schema:givenName | xsd:string | 0 | 1 |  | 55 |
| shape:PersonRDBMSShape | alias:FAMILY_NAME | .schema:familyName | xsd:string | 0 | 1 |  | 55 |
| shape:PersonRDBMSShape | alias:ADDRESS__STREET_ADDRESS | .schema:address.schema:streetAddress | xsd:string | 0 | 1 |  | 55 |
| shape:PersonRDBMSShape | alias:ADDRESS__ADDRESS_LOCALITY | .schema:address.schema:addressLocality | xsd:string | 0 | 1 |  | 55 |
| shape:PersonRDBMSShape | alias:ADDRESS__ADDRESS_REGION | .schema:address.schema:addressRegion | xsd:string | 0 | 1 |  | 55 |
| shape:PersonRDBMSShape | alias:ADDRESS__ADDRESS_COUNTRY | .schema:address:schema:addressCountry | xsd:string | 0 | 1 |  | 55 |
| shape:PersonRDBMSShape | alias:ADDRESS__POSTAL_CODE | .schema:address.schema:postalCode | xsd:string | 0 | 1 |  | 55 |

note - usage of abbreviations should be possible for the physical shape, BUT ONLY in cases where a formula mapping exists to the logical model.

note 2 - the table name for the physical shape can be set in the shapes workbook tab as a parameter to the datasource

| Shape Id  | Datasource |
| ------------- | ------------- |
| shape:PersonRDBMSShape | AwsAurora(AwsTableName:"PERSON") |

## 2. handling one-to-many relationships

In cases where there is a one-to-many relationship we will need to create two tables in the logical model and dependent tables will need to have a foreign key reference (related ticket #897) back to the parent table.

```json 
{
  "ppid": "A102001473032",
  "productName": "PDH_TEP_INT_TEST_011",
  "contributor": [
    {
      "contributorId":"12345",
      "contributorType": "Author",
      "contributorFirstName": "John",
      "contributorSurname": "Doe",
      "primaryAuthorFlag": "YES",
    },
    {
      "contributorId":"23456",
      "contributorType": "Author",
      "contributorFirstName": "Mary",
      "contributorSurname": "Sue",
      "primaryAuthorFlag": "NO",
    }
  ]
}
```

Logical shape

| Shape Id  | Property Id | Formula | Value Type | Value Class | Min Count | Max Count | Stereotype | Max Length |
| ------------- | ------------- | ------------- | ------------- |  ------------- |------------- | ------------- | ------------- | ------------- |
| shape:ProductShape | mdm:ppid | | xsd:string | | 1 | 1 | | 55 |
| shape:ProductShape | mdm:productName  | | xsd:string | | 1 | 1 | | 55 |
| shape:ProductShape | mdm:contributor | | shape:ContributorShape | mdm:Contributor | 0 | unbounded |  | 55 |
| shape:ContributorShape | mdm:contributorId | | xsd:string | | 1 | 1 | | 55  |
| shape:ContributorShape | mdm:contributorType | | xsd:string | | 0 | 1 |  | 55 |
| shape:ContributorShape | mdm:contributorFirstName | | xsd:string | | 1 | 1 | | 55 |
| shape:ContributorShape | mdm:contributorSurname | | xsd:string | | 1 | 1 | | 55 |
| shape:ContributorShape | mdm:primaryAuthorFlag | | xsd:string | | 1 | 1 | | 55 |

In constructing the physical shape we will need to consider
- what naming convention should be used for the child table?  How do we avoid name collisions?
- what naming convention to use for the system-generated foreign key?
- should an array index be created to perserve item ordering?
- What if a primary key for the parent table is not known from input fields and a synthetic key must be created and managed by the system?

Physical Shape

| Shape Id  | Property Id | Formula | Value Type | Min Count | Max Count | Stereotype | Max Length |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| shape:ProductRDBMSShape | alias:PPID | | xsd:string | 1 | 1 |  konig:primaryKey | 55 |
| shape:ProductRDBMSShape | alias:PRODUCT_NAME | | xsd:string | 1 | 1 |  | 55 |
| shape:ProductContributorRDBMSShape | alias:CONTRIBUTOR_ID | |  xsd:string | 1 | 1 | konig:primaryKey | 55 |
| shape:ProductContributorRDBMSShape | alias:PRODUCT__PPID_FK |  ^mdm:contributor.mdm:ppid | xsd:string | 1 | 1 |  | 55 |
| shape:ProductContributorRDBMSShape | alias:CONTRIBUTOR_ID | | xsd:string | 1 | 1 |  | 55 |
| shape:ProductContributorRDBMSShape | alias:CONTRIBUTOR_TYPE | | xsd:string | 1 | 1 |  | 55 |
| shape:ProductContributorRDBMSShape | alias:CONTRIBUTOR_FIRST_NAME | | xsd:string | 1 | 1 |  | 55 |
| shape:ProductContributorRDBMSShape | alias:CONTRIBUTOR_SURNAME | | xsd:string | 1 | 1 |  | 55 |
| shape:ProductContributorRDBMSShape | alias:PRIMARY_AUTHOR_FLAG | | xsd:string | 1 | 1 |  | 55 |

| Shape Id  | Datasource |
| ------------- | ------------- |
| shape:ProductRDBMSShape | AwsAurora(AwsTableName:"MDM_PRODUCT") |
| shape:ProductContributorRDBMSShape | AwsAurora(AwsTableName:"MDM_PRODUCT_CONTRIBUTOR") |

note - the table name for ``shape:ProductContributorRDBMSShape`` is based off the .mdm:contributor path from the PRODUCT table.

## 2b. handling ordering of items from one-to-many relationships

It will often be necessary to preserve the ordering of array items from one-to-many relationships.  If there is no known natural property for representing order, the system may have to add and manage an ordering index in the physical model.

A system-managed ordering index could be added to the ``shape:ProductContributorRDBMSShape`` like this. 

| Shape Id  | Property Id | Formula | Value Type | Min Count | Max Count | Stereotype | Max Length |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| shape:ProductContributorRDBMSShape | alias:SYS_INDEX | |  xsd:integer | 1 | 1 | konig:orderingIndex | |

note - this suggestion implies konig tool support for a new sterotype - ``konig:orderingIndex`` which is used to tell the system this property is used to provide an index into a one-to-many relationship.

**Comment by gmcfall** [comment]
Flattening of one-to-one relationship is already supported.  See #895 

I will add issues for one-to-many relationships, many-to-many relationships, ordered lists.
