### ISSUE TITLE
Support konig:syntheticKey as stereotype

### ISSUE THREAD

**Issue by gmcfall** [konigio/konig#896]
Sometimes we may not have a known natural primary key for an entity that needs to be persisted to a table in the relational physical model.  In these cases it is desirable to define a [synthetic key](https://en.wikipedia.org/wiki/Surrogate_key) in the physical model and mark the field so that tooling knows that the values are system-generated.

example:

| Shape Id  | Property Id | Formula | Value Type | Min Count | Max Count | Stereotype | Max Length |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| shape:MDM_PROD_ORG__PRICING_INFO_ATTRS | alias:STAGE_ID |  | xsd:integer | 1 | 1 | konig:syntheticKey | |

### Acceptance Criteria
* The class `io.konig.core.vocab.Konig` must have a static field that holds the `syntheticKey` stereotype value.
* For any property with the `syntheticKey` stereotype, the konig SQL DDL generator shall declare the column to be a PRIMARY KEY with the AUTO_INCREMENT keyword if it is supported by the host database.

**Comment by zednis** [comment]
It would be desirable for the konig SQL DDL generator to define columns that have been marked as synthetic keys as being primary keys with auto incremment in the table DDL.

```sql
CREATE TABLE MDM_PROD_ORG__PRICING_INFO_ATTRS(
  STAGE_ID INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (STAGE_ID)
);
```
