### ISSUE TITLE
SHACL Shape from Data Dictionary

### ISSUE THREAD

**Issue by gmcfall** [konigio/konig#904]
I want to generate a SHACL Shape description from the entries in a Data Dictionary.  The SHACL Shape generated from a Data Dictionary will always conform to the rules for [RDBMS Shapes](https://github.com/konigio/konig/wiki/RDBMS-Shapes).

A *Data Dictionary* is a spreadsheet with the following columns:

- `Source System`: An abbreviation for the source system
- `Source Object Name`:  A symbolic name for the source object (typically the name of an RDBMS table).
- `Field`: A symbolic name for the a field on the source object (typically a column name).
- `Data Type`: An expression that describes the SQL data type of the field.  Examples: VARCHAR, DATE, DECIMAL
- `Max Length`: The max length of textual fields
- `Decimal Precision`: The max number of digits of a decimal datatype
- `Decimal Scale`: The number of digits to the right of the decimal point in a decimal datatype
- `Constraints`: A controlled vocabulary of terms that describe constraints on the field.  Examples: `Primary Key`, `NULL`, `NOT NULL`, `Unique`.
- `Business Name`: A name/label for the field
- `Business Definition (Optional)`:  A description of the field.
- `Data Steward`: The name of the data steward for this field
- `Security Classification`: Pearson Security classification for this field (e.g. 'Public (DCL1)', Internal Use Only (DCL2)', etc)

## Acceptance Criteria

This information should be used to construct a Shape of the following form:
```
<{shapeURL}> a sh:Shape, konig:RdbmsNodeShape ; 
  sh:property [
    sh:path <{propertyBaseURL}/{field}> ;
    sh:name {businessName} ;
    rdfs:comment {businessDefinitionValue};
    konig:stereotype {stereotypeValue} ; // konig:primaryKey if Primary Key, else omit
    sh:datatype {rdfDatatypeValue} ;
    sh:minCount {minCountValue} ;  // 1 if NOT NULL or Primary Key, else 0
    sh:maxCount {maxCountValue} ;  // should always be 1
    sh:maxLength {maxLengthValue} ; // only used with string or base64Binary datatypes, else omit
    sh:minInclusive {minInclusiveValue} ; // only used with integer datatype
    sh:minExclusive {minExclusiveValue} ; // only used with integer datatype
    konig:decimalScale {decimalScaleValue} ; // only used with decimal datatype
    konig:decimalPrecision {decimalPrecisionValue} ; // only used with decimal datatype
    konig:dataSteward {dataStewardValue} ;
    konig:qualifiedsecurityClassification {securityClassificationURI} ; // see field to URI mapping below
  ]
```
- The value of ``{shapeURL}`` must be generated based on a URL template that accepts the following parameters:
   - ``{SOURCE_SYSTEM}``: The value from the *Source System* column of the Data Dictionary, converted to SNAKE_CASE.
   - ``{SOURCE_OBJECT_NAME}``: The value from the *Source Object Name* column of the Data Dictionary, converted to SNAKE_CASE.
- The value of ``{field}`` should be expressed in SNAKE_CASE
- The value of ``{sourceObjectName}`` should be expressed in SNAKE_CASE
- The value of ``{rdfDatatypeValue}`` should be determined based on the mapping table below
- If the value of ``{rdfDatatypeValue}`` is xsd:integer, include``sh:minInclusive`` and ``sh:maxExclusive`` based on the mapping table below, otherwise omit these properties.
- If the value of ``{rdfDatatypeValue}`` is xsd:decimal, include ``konig:decimalPrecision`` and ``konig:decimalScale`` in the shape, otherwise omit these properties.
- If the Data Dictionary Constraints field includes "Primary Key" include ``konig:stereotype konig:primaryKey ;`` else omit this property.

**Data Dictionary Datatype -> RDF Datatype Mapping**

| Data Dictionary Datatype | RDF Datatype | Uses Max Length | Min Inclusive | Max Exclusive |
| --- | --- | --- | --- | --- |
| CHAR | xsd:string | X | | |
| VARCHAR | xsd:string | X | | |
| VARCHAR2 | xsd:string | X | | |
| TEXT | xsd:string | X | | |
| DATE | xsd:date | | | |
| DATETIME | xsd:dateTime | | | |
| NUMBER | xsd:decimal | | | |
| SMALLINT | xsd:integer | | -32768 | 32767 |
| UNSIGNED SMALLINT | xsd:integer | | 0 | 65535 |
| INT | xsd:integer | | -2,147,483,648 | 2,147,483,647 |
| UNSIGNED INT | xsd:integer | | 0 | 4,294,967,295  |
| BIGINT | xsd:integer | | -9,223,372,036,854,775,808 | 9,223,372,036,854,775,807 |
| UNSIGNED BIGINT | xsd:integer | | 0 | 18,446,744,073,709,551,615  |
| FLOAT | xsd:float | | | |
| DOUBLE | xsd:double | | | |
| DECIMAL | xsd:decimal | | | |
| BINARY | xsd:base64Binary | X | | |
| BOOLEAN | xsd:boolean | | | |

* NUMBER should use ``Decimal Precision`` for the number of allowable digits.

**Security Classification Mapping**

| Data Dictionary Field Value | RDF URI |
| --- | --- |
| Public (DCL1) | dcl:DCL1 |
| Internal Use Only (DCL2) | dcl:DCL2 |
| Confidential (DCL3) | dcl:DCL3 |
| Restricted (DCL4) | dcl:DCL4 |

**Namespaces**

| Namespace | Prefix |
| -- | -- |
| https://schema.pearson.com/ns/dcl/ | dcl |

**Comment by zednis** [comment]
A Data Dictionary template is available in google docs [here](https://docs.google.com/spreadsheets/d/1YdOynh7qIXbRznVgmX7sX6AsxvRKdKRZHrTtjQqOQvY/edit#gid=1604105731)

**Comment by zednis** [comment]
I have added ``NUMBER`` to the Data Dictionary to RDF Datatype mapping table.

In Oracle NUMBER data can be specified with precision (e.g. ``NUMBER(15)``)

When recorded in the Source Data Dictionary, a source field with ``NUMBER(15)`` in an Oracle data source would be recorded as:

| Source Object Name | Field | Data Type | Decimal Precision |
| --- | --- | --- | --- | 
| TEP_INVOICES | CUSTOMER_TRX_ID | Number | 15 |

and the datashape property constraint would look like

```
shape:TEP_INVOICESShape a sh:Shape, konig:RdbmsNodeShape ; 
  sh:property [
    sh:path alias:CUSTOMER_TRX_ID ;
    sh:datatype xsd:decimal ;
    konig:decimalPrecision 15 ;
  ] ;
  .
```
