### ISSUE TITLE
Capture Abbreviation taxonomies in Data Dictionary

### ISSUE THREAD

**Issue by zednis** [konigio/konig#925]
We need to be able to capture abbreviation taxonomies used by datasources in constructing their physical model field names.  

## Acceptance Criteria

The Source Data Dictionary should include the following tabs
- ``Abbreviations``
- ``Settings``

The  'Abbreviations' tab which shall contain the columns `Term` and `Abbreviation`.

Term | Abbreviation
-- | --
MANUFACTURING | MFG
USER_DEFINED_ATTRIBUTES | UDA
ORGANIZATION | ORG

Terms and abbreviations should use the naming conventions from the physical model.  As such all terms and abbreviations should follow physical model naming conventions as described in [Physical Modeling Design Guidelines](https://docs.google.com/document/d/1piQPHjXTcnqAC3gRbQZ4CuwDqpneekDO7whWZ5AnMIw/edit)
 
The ``Settings`` tab shall contain the columns ``Setting Name`` and ``Setting Value``

The Konig tooling must recognize a setting named `abbreviationSchemeIri` whose value
is either a fully-qualified IRI or an IRI template for the `ConceptScheme` in which the abbreviations are defined.

The value is recognized as an IRI template if it contains parameters contained in curly braces.

For instance, it must be possible to specify the following settings:

Setting Name | Setting Value
-- | --
`modelBaseURL` | https://example.com/exampleModel/
`abbreviationSchemeIri` | {modelBaseURL}/AbbreviationScheme

The Konig tooling must expand the `abbreviationSchemeIri` based on other parameters defined on
the settings tab.

The abbreviation tab information should be used to construct a SKOS taxonomy containing all terms and their abbreviations.

```
<{abbreviationSchemeIri}> a skos:ConceptScheme ;
  .

<{abbreviationSchemIri}/{termValue}> a skos:Concept ;
  skos:prefLabel "{termValue}" ;
  konig:abbreviationLabel "{abbreviationValue}" ;
  skos:inScheme <{abbreviationSchemeIri}> ;
  .
``` 

Every shape from the model should include a reference to the skos vocabulary containing the abbreviations.

```
<{shapeIri}> a sh:Shape ;
  konig:usesAbbreviationScheme <{modelBaseURL}/AbbreviationScheme> ;
  .
```

Note that the `shapeIri` value is defined by an IRI template as described in Issues #904 and #945 

## Proposed Terms
- ``konig:abbreviationLabel`` is a datatype property to be used with SKOS Concept values from an abbreviation SKOS ConceptScheme to designate the abbreviation for the term identified by the concept skos:prefLabel
- ``konig:usesAbbreviationScheme`` is an object property to indicate an abbreviation scheme in use, or to be used, for a given data shape

## Related Links
For more information about abbreviations, see [Abbreviations](https://docs.google.com/document/d/1ZD44GorsEHmLcF2QTqStEjfUfBDuuyq6c6RHArgItOw/edit#heading=h.75ahzkoowny) in the discussion about Tabular Shapes.

**Comment by gmcfall** [comment]
@zednis Please add acceptance criteria that explain how this information should be recorded in RDF.

**Comment by gmcfall** [comment]
@zednis Note that I made some tweaks to the acceptance criteria.  In particular, I modified some details about naming the abbreviation scheme and the shapes generated from the data dictionary.
